-- Script de Creación de Tablas y Políticas RLS para CRM Visión Jesús

-- 1. Tabla: usuarios
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario TEXT UNIQUE NOT NULL,
  contrasena TEXT NOT NULL,
  nombre TEXT NOT NULL,
  permisos TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla: proveedores
CREATE TABLE IF NOT EXISTS proveedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  contacto TEXT,
  correo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla: productos
CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  existencia_minima INT DEFAULT 0,
  existencia_actual INT DEFAULT 0,
  costo NUMERIC(12,2) DEFAULT 0,
  precio NUMERIC(12,2) DEFAULT 0,
  clasificacion TEXT,
  proveedor_id BIGINT REFERENCES proveedores(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabla: codigos_barra
CREATE TABLE IF NOT EXISTS codigos_barra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
  codigo TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabla: movimientos_inventario
CREATE TABLE IF NOT EXISTS movimientos_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha TIMESTAMPTZ DEFAULT NOW(),
  producto_id BIGINT REFERENCES productos(id) ON DELETE CASCADE,
  tipo TEXT CHECK (tipo IN ('entrada', 'salida')),
  cantidad INT NOT NULL,
  usuario TEXT,
  motivo TEXT,
  costo_unitario NUMERIC(12,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabla: ventas
CREATE TABLE IF NOT EXISTS ventas (
  id TEXT PRIMARY KEY,
  fecha TIMESTAMPTZ DEFAULT NOW(),
  items JSONB NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  metodo_pago TEXT,
  detalles_pago JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS) en todas las tablas
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE codigos_barra ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos_inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;

-- Crear políticas permisivas para acceso con anon key (clave pública)
CREATE POLICY "Permitir todo acceso a usuarios" ON usuarios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo acceso a proveedores" ON proveedores FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo acceso a productos" ON productos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo acceso a codigos_barra" ON codigos_barra FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo acceso a movimientos_inventario" ON movimientos_inventario FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo acceso a ventas" ON ventas FOR ALL USING (true) WITH CHECK (true);

-- Insertar Datos Iniciales (Semilla / Seed)

INSERT INTO usuarios (usuario, contrasena, nombre, permisos) VALUES
('admin', 'admin123', 'Administrador Principal', ARRAY['facturar', 'productos', 'stock', 'proveedores', 'reportes', 'usuarios']),
('cajero', 'tienda123', 'Cajero Tienda', ARRAY['facturar']),
('inventario', 'inventario123', 'Encargado Stock', ARRAY['productos', 'stock', 'proveedores']),
('reportes', 'reportes123', 'Analista Reportes', ARRAY['reportes'])
ON CONFLICT (usuario) DO NOTHING;

INSERT INTO proveedores (id, nombre, contacto, correo) VALUES
(1, 'Distribuidora La Meseta', '+506 8888-1111', 'ventas@lameseta.com'),
(2, 'Textiles El Ángel', '+506 7777-2222', 'contacto@elangel.com'),
(3, 'FarmaCentral', '+506 6666-3333', 'pedidos@farmacentral.com')
ON CONFLICT (id) DO NOTHING;

INSERT INTO productos (id, nombre, existencia_minima, existencia_actual, costo, precio, clasificacion, proveedor_id) VALUES
(1, 'Galletas Chocochitas', 10, 25, 450, 600, 'Cafetería', 1),
(2, 'Coca Cola 600ml', 15, 8, 700, 1000, 'Cafetería', 1),
(3, 'Jabón de Baño Floral', 5, 12, 350, 500, 'Pulpería', 1),
(4, 'Acetaminofén 500mg', 20, 18, 100, 250, 'Farmacia', 3),
(5, 'Camiseta Visión Jesús Blanca M', 5, 4, 3500, 5000, 'Textiles', 2)
ON CONFLICT (id) DO NOTHING;

INSERT INTO codigos_barra (producto_id, codigo) VALUES
(1, '7501000111222'),
(1, '7501000111223'),
(2, '7501055300075'),
(3, '7501025811005'),
(4, '7501036922001'),
(5, 'VJ-TEE-WHT-M')
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO movimientos_inventario (id, fecha, producto_id, tipo, cantidad, usuario, motivo, costo_unitario) VALUES
(1, NOW() - INTERVAL '24 hours', 1, 'entrada', 25, 'admin', 'Carga inicial de inventario', 450),
(2, NOW() - INTERVAL '12 hours', 2, 'entrada', 10, 'editor_tienda', 'Compra mensual', 700),
(3, NOW() - INTERVAL '2 hours', 1, 'salida', 2, 'caja_ventas', 'Venta Factura FAC-1001', 450),
(4, NOW() - INTERVAL '1 hour', 5, 'salida', 1, 'caja_ventas', 'Venta Factura FAC-1002', 3500)
ON CONFLICT (id) DO NOTHING;

INSERT INTO ventas (id, fecha, items, total, metodo_pago, detalles_pago) VALUES
('FAC-1001', NOW() - INTERVAL '2 hours', '[{"producto_id": 1, "nombre": "Galletas Chocochitas", "cantidad": 2, "precio": 600}]'::jsonb, 1200, 'Efectivo', '{"pagado": 2000, "vuelto": 800}'::jsonb),
('FAC-1002', NOW() - INTERVAL '1 hour', '[{"producto_id": 5, "nombre": "Camiseta Visión Jesús Blanca M", "cantidad": 1, "precio": 5000}]'::jsonb, 5000, 'SINPE Móvil', '{"comprobante": "99827162"}'::jsonb)
ON CONFLICT (id) DO NOTHING;
